apiVersion: v1
kind: Service
metadata:
  name: ai-agent-connector
  namespace: k8spilot
spec:
  selector:
    app: ai-agent-connector
  ports:
    - name: http
      port: 8080
      targetPort: http
